### ISSUE TITLE
Task item

### ISSUE THREAD

**Issue by marwinburesch** [marwinburesch/tasks#11]
Let's add a component for our tasks. It should have two states, which affect the appearance, "not done" (the regular state) and "done" (crossed out).
![image](https://user-images.githubusercontent.com/48555130/126751243-91d95606-9dfc-4cf2-8d78-761b75975aef.png)

**Resources**
- https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/checkbox
- https://developer.mozilla.org/en-US/docs/Web/CSS/text-decoration-line
- https://moderncss.dev/pure-css-custom-checkbox-style/

**Comment by danifosy** [comment]
Please delete the v in the last link :)
